/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GenericAlarmVO { 
    aditionalInfo?: string;
    audio?: boolean;
    canceled?: number;
    date?: Date;
    dealDate?: Date;
    dealTextComent?: string;
    dealUserName?: string;
    dealed?: number;
    elementAlias?: string;
    elementId?: string;
    elementType?: string;
    endDate?: Date;
    id?: string;
    incidencaCode?: string;
    incidencaStatus?: string;
    level?: number;
    name?: string;
    popUpCriticalAdvise?: boolean;
    severity?: number;
    status?: number;
    timeInUid?: boolean;
    type?: number;
    uid?: string;
}
