/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GenericParameterVO { 
    date?: Date;
    edit?: string;
    id?: string;
    maxValue?: string;
    minValue?: string;
    nat?: string;
    paramLabel?: string;
    paramType?: number;
    params?: { [key: string]: GenericParameterVO; };
    type?: string;
    unit?: string;
    value?: string;
    valueRange?: Array<string>;
    visible?: number;
}
