/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Param { 
    color?: string;
    date?: Date;
    deleted?: boolean;
    editable?: boolean;
    elementId?: string;
    elementType?: string;
    historic?: boolean;
    id?: string;
    idElement?: string;
    idParam?: string;
    max?: number;
    min?: number;
    paramParent?: Param;
    paramParentUId?: string;
    paramType?: string;
    params?: { [key: string]: Param; };
    type?: string;
    uid?: string;
    value?: string;
    visible?: number;
}
