/**
 * Toolbar API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ToolBarSubItem } from './toolBarSubItem';


export interface ToolBarItem { 
    itemType?: string;
    itemName?: string;
    icon?: string;
    updateEvent?: string;
    subItems?: ToolBarSubItem;
}
