/**
 * Toolbar API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ToolBarSubItemParam } from './toolBarSubItemParam';


/**
 * Este objeto se usa para definir cada uno de los componetes que salen al pulsar en un toolbar 
 */
export interface ToolBarSubItem { 
    type: string;
    name?: string;
    action?: string;
    paramas?: Array<ToolBarSubItemParam>;
}
